export {default as CategoryItem} from './category-item'
export {default as CategoryBox} from './category-box'
export {default as ListOfFundsMain} from './list-of-funds-main'
export {default as FundDetailsMain} from './fund-details-main'
export {default as Path} from './fund-details-path'
export {default as FundDetailsContent} from './fund-details-content'
export {default as SideBar} from './fund-details-side-bar'
